# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®å…ˆé ­ã«æ”¹è¡Œã‚’è¡¨ç¤ºã—ãªã„
add_newline = false

[aws]
disabled = true

[gcloud]
disabled = true

[git_branch]
# symbol = "ğŸŒ± "
# symbol = "î‚  "
style = "bold green"

[git_status]
style = "green"

[golang]
format = " [$symbol$version]($style)"

[java]
format = " [$symbol$version]($style)"

[ruby]
format = " [$symbol$version]($style)"
symbol = "â™¦ "

[julia]
format = " [$symbol$version]($style)"

[lua]
format = " [$symbol$version]($style)"

[nodejs]
format = " [$symbol$version]($style)"

[perl]
format = " [$symbol$version]($style)"

[rust]
format = " [$symbol$version]($style)"

[terraform]
format = " [$symbol$version]($style)"

[custom]

[custom.tab]
description = "The current tab in the tab terminal multiplexer"
command = "tab --starship"
when = "tab --starship"
shell = ["sh"]
format = " [$output]($style) "
style = "bold blue"
