shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.env]
local = "~/dotfiles/zsh"
use = ["env.zsh"]

[plugins.options]
local = "~/dotfiles/zsh/config"
use = ["options.zsh"]

[plugins.keybinds]
local = "~/dotfiles/zsh/config"
use = ["keybinds.zsh"]

[plugins.history]
local = "~/dotfiles/zsh/config"
use = ["history.zsh"]

[plugins.completion]
local = "~/dotfiles/zsh/config"
use = ["completion.zsh"]

[plugins.aliases]
local = "~/dotfiles/zsh/config"
use = ["aliases.zsh"]

[plugins.functions]
local = "~/dotfiles/zsh/config"
use = ["functions.zsh"]

[plugins.integrations]
local = "~/dotfiles/zsh/config"
use = ["integrations.zsh"]

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.mise]
inline = 'eval "$(~/bin/mise activate zsh)"'

[plugins.direnv]
inline = 'eval "$(direnv hook zsh)"'

[plugins.git-wt]
inline = 'eval "$(git wt --init zsh)"'

[plugins.interactive-tools]
local = "~/dotfiles/zsh"
use = ["{skim,navi,notify,ghq}.zsh"]
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.private]
local = "~/dotfiles/"
use = ["zshrc.private"]
