[[actions]]
action = "file.link"
source = "{{ user.home_dir }}/dotfiles/config/hypr"
target = "{{ user.config_dir }}/hypr"

[[actions]]
action = "file.link"
source = "{{ user.home_dir }}/dotfiles/config/waybar"
target = "{{ user.config_dir }}/waybar"

[[actions]]
action = "file.link"
source = "{{ user.home_dir }}/dotfiles/config/mako"
target = "{{ user.config_dir }}/mako"

[[actions]]
action = "file.link"
source = "{{ user.home_dir }}/dotfiles/config/fuzzel"
target = "{{ user.config_dir }}/fuzzel"
